plugins {
    id 'java'
}

group = 'ru.filinworld'
version = '1.1.0'

repositories {
    mavenCentral()
    maven { url = 'https://maven.enginehub.org/repo/' }
}

dependencies {
    compileOnly files('libs/patched_1.16.5.jar')
    compileOnly files('libs/LuckPerms-Bukkit-5.4.102.jar')
    compileOnly 'com.sk89q.worldguard:worldguard-bukkit:7.0.7'
    compileOnly 'com.sk89q.worldedit:worldedit-bukkit:7.2.12'
}

java {
    sourceCompatibility = JavaVersion.VERSION_16
    targetCompatibility = JavaVersion.VERSION_16
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}