name: FilinPrivates
version: 1.0.0
main: ru.filinworld.plugin.FilinPrivates
api-version: 1.16
author: The_Swalop "Команда FilinWorld"
description: Система приватов Filin World

commands:
  rg:
    description: Команда для управления приватами
    usage: /rg <claim|add|remove|info>